In [5]:
import PyPDF2
import pandas as pd
import os

# List of U.S. state names
state_names = [
    "ALABAMA", "ALASKA", "ARIZONA", "ARKANSAS", "CALIFORNIA", "COLORADO", "CONNECTICUT", "DELAWARE", "FLORIDA", 
    "GEORGIA", "HAWAII", "IDAHO", "ILLINOIS", "INDIANA", "IOWA", "KANSAS", "KENTUCKY", "LOUISIANA", "MAINE", 
    "MARYLAND", "MASSACHUSETTS", "MICHIGAN", "MINNESOTA", "MISSISSIPPI", "MISSOURI", "MONTANA", "NEBRASKA", 
    "NEVADA", "NEW HAMPSHIRE", "NEW JERSEY", "NEW MEXICO", "NEW YORK", "NORTH CAROLINA", "NORTH DAKOTA", "OHIO", 
    "OKLAHOMA", "OREGON", "PENNSYLVANIA", "RHODE ISLAND", "SOUTH CAROLINA", "SOUTH DAKOTA", "TENNESSEE", "TEXAS", 
    "UTAH", "VERMONT", "VIRGINIA", "WASHINGTON", "WEST VIRGINIA", "WISCONSIN", "WYOMING"
]

def extract_table_from_pdf(pdf_path):
    with open(pdf_path, 'rb') as file:
        reader = PyPDF2.PdfReader(file)
        
        # Find the start and end pages of the table
        start_page = None
        end_page = None
        for i, page in enumerate(reader.pages):
            if "ALABAMA" in page.extract_text():
                start_page = i
            if "WYOMING" in page.extract_text():
                end_page = i
                break
        
        # If start or end page is not found, return an empty DataFrame
        if start_page is None or end_page is None:
            return pd.DataFrame()
        
        # Extract text from the identified range of pages
        text = ""
        for page_num in range(start_page, end_page + 1):
            text += reader.pages[page_num].extract_text()

    # Split the text into lines
    lines = text.split('\n')

    # Initialize lists to store data
    seats = []
    states = []
    names = []
    lq_scores = []

    # Variables to keep track of current state
    current_state = None

    # Iterate through the lines to extract data
    for line in lines:
        if any(state in line for state in state_names):
            current_state = line.replace("(cont.)", "").strip()
        elif any(char.isdigit() for char in line) and "%" in line:
            parts = line.split()
            seats.append(parts[0])
            names.append(' '.join(parts[1:-1]))
            lq_scores.append(parts[-1])
            states.append(current_state)

    # Create a pandas DataFrame
    df = pd.DataFrame({
        'Seat': seats,
        'State': states,
        'Name': names,
        'LQ Score': lq_scores
    })

    # Extract the year from the file name
    year = os.path.basename(pdf_path).split('.')[0]
    df['Year'] = year

    # Remove the '%' symbol, fill NaN values with 0, and then convert to integer
    df['LQ Score'] =  df['LQ Score'].str.extract('(\d+)').fillna(0).astype(int)


    # Clean up the 'Name' column by removing any unwanted characters
    df['Name'] = df['Name'].str.replace('[^a-zA-Z\s.]|X', '', regex=True).str.strip()
    df['Name'] = df['Name'].str.replace('A Newsletter for Liberal', '', regex=False).str.strip()

    return df

# Example usage:
base_path = "/Users/sakibanwar/Library/CloudStorage/OneDrive-TheUniversityofWinchester/Untitled Folder 1/downloaded_pdfs"
pdf_paths = [os.path.join(base_path, f"{year}.pdf") for year in range(2010, 2020)]  # List of paths to your PDF files
dfs = []  # List to store DataFrames for each PDF

for pdf_path in pdf_paths:
    dfs.append(extract_table_from_pdf(pdf_path))

# Combine all DataFrames into one
final_df = pd.concat(dfs, ignore_index=True)
print(final_df)

     Seat      State           Name  LQ Score  Year
0       4    ALABAMA     Aderholt R         0  2010
1       6    ALABAMA    Bachus S. R         0  2010
2       1    ALABAMA       Bonner R         0  2010
3       2    ALABAMA       Bright D         0  2010
4       7    ALABAMA     Davis A. D         0  2010
...   ...        ...            ...       ...   ...
4291    5  WISCONSIN  Sensenbrenner         0  2019
4292    6  WISCONSIN       Grothman         0  2019
4293    7  WISCONSIN   Duffy IIIIII         0  2019
4294    8  WISCONSIN      Gallagher        10  2019
4295   AL    WYOMING         Cheney         5  2019

[4296 rows x 5 columns]

In [3]:
final_df

     Seat      State           Name  LQ Score  Year
0       4    ALABAMA     Aderholt R         0  2010
1       6    ALABAMA    Bachus S. R         0  2010
2       1    ALABAMA       Bonner R         0  2010
3       2    ALABAMA       Bright D         0  2010
4       7    ALABAMA     Davis A. D         0  2010
...   ...        ...            ...       ...   ...
4291    5  WISCONSIN  Sensenbrenner         0  2019
4292    6  WISCONSIN       Grothman         0  2019
4293    7  WISCONSIN   Duffy IIIIII         0  2019
4294    8  WISCONSIN      Gallagher        10  2019
4295   AL    WYOMING         Cheney         5  2019

[4296 rows x 5 columns]

In [7]:
final_df.to_csv('ADA_Score_2010_2019.csv',index=False)